### PR TITLE
Add Broadcast TX to Explorer UI

### PR DESCRIPTION
**Pull request by zh**
Issue #49 (bounty 9)

* **mainnet JSON file** updated to add an entry for the `/tx/broadcast` endpoint
* **testnet JSON file** updated to add an entry for the `/tx/broadcast` endpoint

Note: This call seems a little strange - it is a **POST request, but the body is not JSON, but a string**. Needed to implement a new type in the JSON file - `'textbody'` with value the raw string to be passed. This will also trigger curl `content-type` to be switched to `'text/plain'`.

### CODE REVIEW

**Comment by christroutner** [comment]
Hmm.. That's strange. The [bch-api code](https://github.com/Permissionless-Software-Foundation/bch-api/blob/master/src/routes/v3/electrumx.js#L541) shows the hex coming through in the `body`. I know Rosco had originally coded it as plain text.

I'll play with the code. Is this bounty ready for review?

**Comment by zh** [comment]
Yes. It is ready for review.

**Comment by zh** [comment]
> ..I know Rosco had originally coded it as plain text.

All other POST calls have **JSON as a body**. For example `{ txhex: "201010202020...." }`. Because of this, until now all `curl` examples had `'Content-Type':'application/json'`. But this call for some reason came **not as a JSON body, but directly as a string body**. And the `'Content-Type' `is `'text/plain'`

**Comment by christroutner** [comment]
Sorry to take so long to review this.

When I click the 'Execute' button, I get this error:

{
  "success": false,
  "error": "request body must be a string."
}

We had a previous discussion about how the content-type was text and not JSON. I think when you made these changes, they were to an older version of bch-api. I updated this endpoint in bch-api to access a JSON object with txHex property containing the hex:

https://github.com/Permissionless-Software-Foundation/bch-api/blob/master/src/routes/v3/electrumx.js#L541

Can you update this PR to reflect these changes? The bch-api changes are live on the production server now.

**Comment by christroutner** [comment]
This is the curl statement that should work with this endpoint, from [the bch-api documentation](https://api.fullstack.cash/docs/#api-ElectrumX_/_Fulcrum-Broadcast_a_raw_transaction):

`curl -X POST "https://api.fullstack.cash/v3/electrumx/tx/broadcast" -H "accept: application/json" -H "Content-Type: application/json" -d '{"txHex":"020000000265d13ef402840c8a51f39779afb7ae4d49e4b0a3c24a3d0e7742038f2c679667010000006441dd1dd72770cadede1a7fd0363574846c48468a398ddfa41a9677c74cac8d2652b682743725a3b08c6c2021a629011e11a264d9036e9d5311e35b5f4937ca7b4e4121020797d8fd4d2fa6fd7cdeabe2526bfea2b90525d6e8ad506ec4ee3c53885aa309ffffffff65d13ef402840c8a51f39779afb7ae4d49e4b0a3c24a3d0e7742038f2c679667000000006441347d7f218c11c04487c1ad8baac28928fb10e5054cd4494b94d078cfa04ccf68e064fb188127ff656c0b98e9ce87f036d183925d0d0860605877d61e90375f774121028a53f95eb631b460854fc836b2e5d31cad16364b4dc3d970babfbdcc3f2e4954ffffffff035ac355000000000017a914189ce02e332548f4804bac65cba68202c9dbf822878dfd0800000000001976a914285bb350881b21ac89724c6fb6dc914d096cd53b88acf9ef3100000000001976a91445f1f1c4a9b9419a5088a3e9c24a293d7a150e6488ac00000000"}'`

**Comment by christroutner** [comment]
150 PSF tokens rewarded. TXID: 4ecc17f847df50036c74212cae9336e4bd2d369b6ef566e8f7f20caded17ac02

**Comment by christroutner** [comment]
:tada: This PR is included in version 1.19.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Pull request merged**
